title: Anthropic Adapter
description: The adapter integrates Anthropic AI models into Modelflow  AI.
shortDescription: The adapter for the Anthropic API client.
examples: true
usage: |
    First, initialize the client:

    ```php
    use ModelflowAi\Anthropic\Anthropic;

    $client = Anthropic::client('your-api-key');
    ```

    Then, you can use the `AnthropicChatModelAdapter`:

    ```php
    use ModelflowAi\Chat\Adapter\AIChatAdapterInterface;
    use ModelflowAi\Chat\AIChatRequestHandler;
    use ModelflowAi\Chat\Request\AIChatRequest;
    use ModelflowAi\Chat\Request\Message\AIChatMessage;
    use ModelflowAi\Chat\Request\Message\AIChatMessageRoleEnum;
    use ModelflowAi\DecisionTree\DecisionTree;
    use ModelflowAi\DecisionTree\Criteria\CapabilityCriteria;
    use ModelflowAi\DecisionTree\DecisionRule;
    use ModelflowAi\Anthropic\Model;
    use ModelflowAi\AnthropicAdapter\Chat\AnthropicChatAdapter;
    use ModelflowAi\PromptTemplate\ChatPromptTemplate;
    
    $modelAdapter = new AnthropicChatAdapter($client, Model::CLAUDE_3_HAIKU);
    
    /** @var DecisionTreeInterface<AIChatRequest, AIChatAdapterInterface> $decisionTree */
    $decisionTree = new DecisionTree([
        new DecisionRule($modelAdapter, [CapabilityCriteria::SMART]),
    ]);
    $handler = new AIChatRequestHandler($decisionTree);
    
    $response = $handler->createRequest(
        ...ChatPromptTemplate::create(
            new AIChatMessage(AIChatMessageRoleEnum::SYSTEM, 'You are an {feeling} bot'),
            new AIChatMessage(AIChatMessageRoleEnum::USER, 'Hello {where}!'),
        )->format(['where' => 'world', 'feeling' => 'angry']),
    )
        ->addCriteria(CapabilityCriteria::SMART)
        ->build()
        ->execute();
    
    echo \sprintf('%s: %s', $response->getMessage()->role->value, $response->getMessage()->content);
    ```
