title: Mistral Adapter
description: The adapter integrates Mistral AI models into Modelflow  AI.
shortDescription: The adapter for the Mistral API client.
examples: true
usage: |
    First, initialize the client:

    ```php
    use ModelflowAi\Mistral\Mistral;

    $client = Mistral::client('your-api-key');
    ```

    Then, you can use the `MistralChatModelAdapter`:

    ```php
    use ModelflowAi\Core\AIRequestHandler;
    use ModelflowAi\DecisionTree\DecisionTree;
    use ModelflowAi\DecisionTree\DecisionRule;
    use ModelflowAi\Core\Request\Criteria\CapabilityCriteria;
    use ModelflowAi\Mistral\Model;
    use ModelflowAi\MistralAdapter\Model\MistralChatModelAdapter;

    $modelAdapter = new MistralChatModelAdapter($client, Model::LARGE);
    $decisionTree = new DecisionTree([
        new DecisionRule($modelAdapter, [CapabilityCriteria::SMART]),
    ]]);
    $handler = new AIRequestHandler($decisionTree);

    /** @var AIChatResponse $response */
    $response = $handler->createChatRequest(
        ...ChatPromptTemplate::create(
            new AIChatMessage(AIChatMessageRoleEnum::SYSTEM, 'You are an {feeling} bot'),
            new AIChatMessage(AIChatMessageRoleEnum::USER, 'Hello {where}!'),
        )->format(['where' => 'world', 'feeling' => 'angry']),
    )
        ->addCriteria(PrivacyCriteria::MEDIUM)
        ->build()
        ->execute();
    
    echo \sprintf('%s: %s', $response->getMessage()->role->value, $response->getMessage()->content);
    ```

    And the `EmbeddingsAdapter`:

    ```php
    use ModelflowAi\MistralAdapter\Embeddings\MistralEmbeddingAdapter;

    $embeddingsAdapter = new MistralEmbeddingAdapter($client);
    $vector = $embeddingsAdapter->embedText('your-input');
    ```
