title: Mistral Adapter
description: The adapter integrates Mistral AI models into Modelflow  AI.
shortDescription: The adapter for the Mistral API client.
examples: true
usage: |
    First, initialize the client:

    ```php
    use ModelflowAi\Mistral\Mistral;

    $client = Mistral::client('your-api-key');
    ```

    Then, you can use the `MistralChatModelAdapter`:

    ```php
    use ModelflowAi\Chat\Adapter\AIChatAdapterInterface;
    use ModelflowAi\Chat\AIChatRequestHandler;
    use ModelflowAi\Chat\Request\AIChatRequest;
    use ModelflowAi\Chat\Request\Message\AIChatMessage;
    use ModelflowAi\Chat\Request\Message\AIChatMessageRoleEnum;
    use ModelflowAi\DecisionTree\DecisionTree;
    use ModelflowAi\DecisionTree\Criteria\CapabilityCriteria;
    use ModelflowAi\DecisionTree\DecisionRule;
    use ModelflowAi\Mistral\Model;
    use ModelflowAi\MistralAdapter\Chat\MistralChatAdapter;
    use ModelflowAi\PromptTemplate\ChatPromptTemplate;

    $modelAdapter = new MistralChatAdapter($client, Model::LARGE);
    
    /** @var DecisionTreeInterface<AIChatRequest, AIChatAdapterInterface> $decisionTree */
    $decisionTree = new DecisionTree([
        new DecisionRule($modelAdapter, [CapabilityCriteria::SMART]),
    ]);
    $handler = new AIChatRequestHandler($decisionTree);

    $response = $handler->createRequest(
        ...ChatPromptTemplate::create(
            new AIChatMessage(AIChatMessageRoleEnum::SYSTEM, 'You are an {feeling} bot'),
            new AIChatMessage(AIChatMessageRoleEnum::USER, 'Hello {where}!'),
        )->format(['where' => 'world', 'feeling' => 'angry']),
    )
        ->addCriteria(CapabilityCriteria::SMART)
        ->build()
        ->execute();
    
    echo \sprintf('%s: %s', $response->getMessage()->role->value, $response->getMessage()->content);
    ```

    And the `EmbeddingsAdapter`:

    ```php
    use ModelflowAi\MistralAdapter\Embeddings\MistralEmbeddingAdapter;

    $embeddingsAdapter = new MistralEmbeddingAdapter($client);
    $vector = $embeddingsAdapter->embedText('your-input');
    ```
