services:
    qdrant:
        image: qdrant/qdrant:v1.7.4
        ports:
            - "6333:6333"
        volumes:
            - qdrant-data:/qdrant/storage

    ollama:
        image: ollama/ollama
        ports:
            - "21434:11434"
        volumes:
            - ollama-data:/root/.ollama

volumes:
    qdrant-data:
    ollama-data:
