name: Quality Assurance

on:
    pull_request:
    push:
        branches:
            - '[0-9]+.[0-9]+'

jobs:
    anthropic:
        name: Anthropic
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/anthropic'
            docker: false

    anthropic-adapter:
        name: Anthropic Adapter
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/anthropic-adapter'
            docker: false

    api-client:
        name: Api-Client
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/api-client'
            docker: false

    core:
        name: Core
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/core'
            docker: false

    decision-tree:
        name: Core
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/decision-tree'
            docker: false

    elasticsearch-embeddings-store:
        name: Elasticsearch Embeddings Store
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/elasticsearch-embeddings-store'
            docker: true

    embeddings:
        name: Embeddings
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/embeddings'
            docker: false

    experts:
        name: Experts
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/experts'
            docker: false

    image:
        name: Image
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/image'
            docker: false

    mistral:
        name: Mistral
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/mistral'
            docker: false

    mistral-adapter:
        name: Mistral Adapter
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/mistral-adapter'
            docker: false

    ollama:
        name: Ollama
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/ollama'
            docker: false

    ollama-adapter:
        name: Ollama Adapter
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/ollama-adapter'
            docker: false

    openai-adapter:
        name: OpenAI Adapter
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/openai-adapter'
            docker: false

    prompt-template:
        name: Prompt Template
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/prompt-template'
            docker: false

    qdrant-embeddings-store:
        name: Qdrant Embeddings Store
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/qdrant-embeddings-store'
            docker: true

    tools:
        name: Tools
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/tools'
            docker: false

    symfony-integration:
        name: Symfony Integration
        uses: ./.github/workflows/test.yml
        with:
            directory: 'integrations/symfony'
            docker: false
